### ISSUE TITLE
entity authors get exported to type Person in schema.org

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/cff-converter-python#239]
Given the following `CITATION.cff` contents

```yaml
authors:
  - name: Team
cff-version: 1.2.0
title: Title
message: message
```

converting to schema.org with `cffconvert -f schema.org` yields:

```json
{
  "@context": "https://schema.org",
  "@type": "SoftwareSourceCode",
  "author": [
    {
      "@type": "Person",
      "name": "Team"
    }
  ],
  "name": "Title"
}
```
Instead of Person, there should be another type.
