### ISSUE TITLE
Dataset becomes a SoftwareSourceCode when exporting to schemaorg

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/cff-converter-python#240]
Given the following `CITATION.cff` contents

```yaml
authors:
  - name: Team
cff-version: 1.2.0
title: Title
type: dataset
message: message
```

converting to schema.org with `cffconvert -f schema.org` yields:

```json
{
  "@context": "https://schema.org",
  "@type": "SoftwareSourceCode",
  "author": [
    {
      "@type": "Person",
      "name": "Team"
    }
  ],
  "name": "Title"
}
```
Instead of SoftwareSourceCode there should be another type.
