### ISSUE TITLE
CFF validate preferred-citation / proceedings / publisher

### ISSUE THREAD

**Issue by hayesall** [citation-file-format/cff-converter-python#265]
I'm validating a CFF file, but I'm getting a `jsonschema.exceptions.ValidationError` when trying to validate anything under `preferred-citation/publisher`.

I'm not sure whether this is a bug or my misunderstanding of how objects vs. lists are interpreted in this format.

## Reproducible Example

`CITATION.cff` file:

```yaml
cff-version: 1.2.0

title: 'My great title'
authors:
  - family-names: "Persington"
    given-names: "Person"
message: >-
  Please use the 'preferred-citation'.

preferred-citation:
  type: proceedings
  authors:
    - family-names: "Persington"
      given-names: "Person"
  publisher:
    - address: "Something"
  doi: "10.0000/00000"
  title: "My great title"
  start: 1
  end: 8
  year: 2020
```

**Version info**:

```bash
# cff-version: 1.2.0
cffconvert --version
2.0.0
```

## Full Traceback

According to the traceback, there should be keys for `address`, `alias`, etc., but the `publisher` key seems to be interpreted as a list instead of an object:

It looks like this is the important part:

```console
jsonschema.exceptions.ValidationError: [{'address': 'Something'}] is not of type 'object'

Failed validating 'type' in schema['properties']['preferred-citation']['properties']['publisher']:

On instance['preferred-citation']['publisher']:
    [{'address': 'Something'}]
```

The full traceback is quite detailed, but is copied here:

<details>
<summary>View full traceback</summary>

```console
jsonschema.exceptions.ValidationError: [{'address': 'Something'}] is not of type 'object'

Failed validating 'type' in schema['properties']['preferred-citation']['properties']['publisher']:
    {'additionalProperties': False,
     'description': 'An entity, i.e., an institution, team, research '
                    'group, company, conference, etc., as opposed to a '
                    'single natural person.',
     'properties': {'address': {'$ref': '#/definitions/address',
                                'description': "The entity's address."},
                    'alias': {'$ref': '#/definitions/alias',
                              'description': "The entity's alias."},
                    'city': {'$ref': '#/definitions/city',
                             'description': "The entity's city."},
                    'country': {'$ref': '#/definitions/country',
                                'description': "The entity's country."},
                    'date-end': {'$ref': '#/definitions/date',
                                 'description': "The entity's ending date, "
                                                'e.g., when the entity is '
                                                'a conference.'},
                    'date-start': {'$ref': '#/definitions/date',
                                   'description': "The entity's starting "
                                                  'date, e.g., when the '
                                                  'entity is a '
                                                  'conference.'},
                    'email': {'$ref': '#/definitions/email',
                              'description': "The entity's email address."},
                    'fax': {'$ref': '#/definitions/fax',
                            'description': "The entity's fax number."},
                    'location': {'description': "The entity's location, "
                                                'e.g., when the entity is '
                                                'a conference.',
                                 'minLength': 1,
                                 'type': 'string'},
                    'name': {'description': "The entity's name.",
                             'minLength': 1,
                             'type': 'string'},
                    'orcid': {'$ref': '#/definitions/orcid',
                              'description': "The entity's orcid."},
                    'post-code': {'$ref': '#/definitions/post-code',
                                  'description': "The entity's post code."},
                    'region': {'$ref': '#/definitions/region',
                               'description': "The entity's region."},
                    'tel': {'$ref': '#/definitions/tel',
                            'description': "The entity's telephone "
                                           'number.'},
                    'website': {'$ref': '#/definitions/url',
                                'description': "The entity's website."}},
     'required': ['name'],
     'type': 'object'}

On instance['preferred-citation']['publisher']:
    [{'address': 'Something'}]
```

</details>

**Comment by hayesall** [comment]
Figured it out, hope it's helpful to others at least.

The keys were provided incorrectly. The hyphens implied list syntax when they should have been key-value syntax. Specify them as:

```yaml
  publisher:
    name: "Publisher Name"
    address: "1 Example Road"
```

Also see the `schema-guide`: https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionsreferencepublisher

---

Complete working example:

```yaml
cff-version: 1.2.0

title: 'My great title'
authors:
  - family-names: "Persington"
    given-names: "Person"
message: >-
  Please use the 'preferred-citation'.

preferred-citation:
  type: proceedings
  authors:
    - family-names: "Persington"
      given-names: "Person"
  publisher:
    name: "Publisher Name"
    address: "1 Example Road"
  doi: "10.0000/00000"
  title: "My great title"
  start: 1
  end: 8
  year: 2020
```
