### ISSUE TITLE
Author email address is not transferred

### ISSUE THREAD

**Issue by led02** [citation-file-format/cff-converter-python#285]
When applying `cffconvert` in a new project, I realized that the author email addresses are not transferred (e.g., to codemeta).

E.g., if you have the following `CITATION.cff`:

```yaml
cff-version: 1.2.0
title: Test File
message: See the bug
type: software
authors:
  - given-names: Michael
    family-names: Meinel
    email: michael.meinel@dlr.de
```

Running `cffconvert -f codemeta` results in the following `codemeta.json`:

```json
{
  "@context": "https://doi.org/10.5063/schema/codemeta-2.0",
  "@type": "SoftwareSourceCode",
  "author": [
    {
      "@type": "Person",
      "familyName": "Meinel",
      "givenName": "Michael"
    }
  ],
  "name": "Test File"
}
```

The email address is not transferred but I would expect to have a field `email` in the `author[0]` node.
