### ISSUE TITLE
should `name` take precedence over `alias`?

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/cff-converter-python#308]
state: 0c11be31eb5967fdd0bf3c41709496005fafa240

```yaml
authors:
  - name: The soccer team members
    alias: Rafa
cff-version: "1.2.0"
message: "test of author inputs"
title: the title
```

is currently converted to

```json
{
  "creators": [
    {
      "name": "Rafa"
    }
  ],
  "title": "the title",
  "upload_type": "software"
}
```

The tradeoff happens for:

- apalike
- bibtex
- endnote
- ris
- zenodo

but not schema.org or codemeta, because they define `alternateName` so both the information from `name` as well as that from  `alias` can be retained.
